[package]
name = "async-kartoffel"
version = "0.1.0"
edition = "2021"

[features]
default = ["serial-panic", "critical-section-impl"]

# Enables printing of the panic message to the serial port
serial-panic = []
# Provides an implementation for the critical-section crate
critical-section-impl = []

[dependencies]
critical-section = "1.2.0"
spin = "0.9.8"
talc = "4.4.2"

[dev-dependencies]
embassy-executor = { version = "0.6.3", features = ["arch-spin", "executor-thread"] }
static_cell = "2.1.0"
