[package]
name = "async-kartoffel"
version = "0.1.0"
edition = "2021"

[features]
default = ["serial-panic", "critical-section-impl"]

# Enables printing of the panic message to the serial port
serial-panic = []
# Provides an implementation for the critical-section crate
critical-section-impl = []

[dependencies]
kartoffel = { git = "https://github.com/Patryk27/kartoffels" }
critical-section = "1.2.0"
spin = "0.9.8"
talc = "4.4.2"
heapless = "0.8.0"
embassy-futures = "0.1.1"

[dev-dependencies]
embassy-executor = { version = "0.6.3", features = ["arch-spin", "executor-thread"] }
static_cell = "2.1.0"
embassy-sync = "0.6.2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
