[package]
name = "async-algorithm"
version.workspace = true
edition.workspace = true

[dependencies]
heapless.workspace = true
embassy-futures.workspace = true
async-kartoffel-generic.workspace = true
