[package]
name = "kartoffel-gps"
version.workspace = true
edition.workspace = true

[dependencies]
async-kartoffel-generic.workspace = true
async-algorithm.workspace = true
phf_shared.workspace = true
heapless.workspace = true
rand.workspace = true
