[package]
name = "kartoffel-gps"
version = "0.1.0"
edition = "2021"

[dependencies]
phf_shared.workspace = true
async-kartoffel = {path = "../../crates/async-kartoffel", default-features = false}

[lib]
test = false
